### PR TITLE
fix website deployment to s3

### LINKED ISSUE #672: Gulp setup doesn't show the bucket URL for the frontend deployment

### PR DESCRIPTION
**Pull request by dknochen**
- fixes #672

### CODE REVIEW

File: tasks/s3.js [hunk 1]
```diff
@@ -32,6 +32,29 @@ var init = function() {
     s3 = new AWS.S3(config);
 };
 
+var checkWebsiteAvailable = function(){
+    var defered = Q.defer();
+    var url = 'http://' + bucketName + '.s3-website-' + region + '.amazonaws.com/index.html';
```
Comment (wcandillon) [inline tasks/s3.js]: @dknochen Can you log this url somewhere?
